package scr;
// Generated 29/04/2017 16:23:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long id;
     private String nomeresponsavel;
     private String bairro;
     private String telefone;
     private Date data;
     private String pif;

    public Usuario() {
    }

    public Usuario(long id, String nomeresponsavel, String bairro, String telefone, Date data, String pif) {
       this.id = id;
       this.nomeresponsavel = nomeresponsavel;
       this.bairro = bairro;
       this.telefone = telefone;
       this.data = data;
       this.pif = pif;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNomeresponsavel() {
        return this.nomeresponsavel;
    }
    
    public void setNomeresponsavel(String nomeresponsavel) {
        this.nomeresponsavel = nomeresponsavel;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getPif() {
        return this.pif;
    }
    
    public void setPif(String pif) {
        this.pif = pif;
    }




}


